export const BOOTSTRAP = 'BOOTSTRAP';
export const BOOTSTRAP_DATA = 'BOOTSTRAP_DATA';
export const BOOTSTRAP_ERROR = 'BOOTSTRAP_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_DATA = 'LOGOUT_DATA';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const CATALOGUE_UPDATE = 'CATALOGUE_UPDATE';
export const CATALOGUE_UPDATED = 'CATALOGUE_UPDATED';
export const CATALOGUE_SET_ACTIVE_FILTER_INDEX = 'CATALOGUE_SET_ACTIVE_FILTER_INDEX';
export const CATALOGUE_SET_QUERY = 'CATALOGUE_SET_QUERY';
export const CATALOGUE_SET_ACTIVE_DATASET_ID = 'CATALOGUE_SET_ACTIVE_DATASET_ID';

export const DATE_DIMENSIONS_DATA = 'DATE_DIMENSIONS_DATA';

export const DATASETS_REQUEST = 'DATASETS_REQUEST';
export const DATASETS_DATA = 'DATASETS_DATA';

export const ITEM_DETAIL_REQUEST = 'ITEM_DETAIL_REQUEST';
export const ITEM_DETAIL_DATA = 'ITEM_DETAIL_DATA';

export const BUCKETS_SELECT_VISUALIZATION_TYPE = 'BUCKETS_SELECT_VISUALIZATION_TYPE';
export const BUCKETS_SET_BUCKET_ITEM_COLLAPSED = 'BUCKETS_SET_BUCKET_ITEM_COLLAPSED';
export const BUCKETS_SET_BUCKET_ITEM_SHOW_IN_PERCENT = 'BUCKETS_SET_BUCKET_ITEM_SHOW_IN_PERCENT';
export const BUCKETS_SET_BUCKET_ITEM_SHOW_POP = 'BUCKETS_SET_BUCKET_ITEM_SHOW_POP';
export const BUCKETS_SET_BUCKET_ITEM_ADD_FILTER = 'BUCKETS_SET_BUCKET_ITEM_ADD_FILTER';
export const BUCKETS_SET_BUCKET_ITEM_REMOVE_FILTER = 'BUCKETS_SET_BUCKET_ITEM_REMOVE_FILTER';
export const BUCKETS_SET_BUCKET_ITEM_AGGREGATION = 'BUCKETS_SET_BUCKET_ITEM_AGGREGATION';
export const BUCKETS_SET_BUCKET_ITEM_DIMENSION = 'BUCKETS_SET_BUCKET_ITEM_DIMENSION';
export const BUCKETS_SET_BUCKET_ITEM_GRANULARITY = 'BUCKETS_SET_BUCKET_ITEM_GRANULARITY';
